# Generated by Django 6.0 on 2026-01-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hii', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
